In [ ]:
# Kingston PM2.5 concentrations

In [39]:
import pandas as pd
import geopandas as gpd
import folium
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import contextily as cx

ModuleNotFoundError: No module named 'contextily'

In [2]:
fname_pm2_5_conc = "LAEI2022_V1_PM25.csv"

In [6]:
df = pd.read_csv(fname_pm2_5_conc)

In [23]:
df = df.rename(columns={"x": "Easting", "y": "Northing"})

         Easting  Northing      conc
4130441   518500    169900  8.750484
4130442   518520    169900  8.688523
4130443   518540    169900  8.667526
4130444   518560    169900  8.658435
4130445   518580    169900  8.656651

In [24]:
percentile_90 = df[df["conc"] > np.percentile(df["conc"], 90)]

In [34]:
gdf = gpd.GeoDataFrame(percentile_90, 
                        geometry=gpd.points_from_xy(percentile_90["Easting"], percentile_90["Northing"]),
                        crs="EPSG:27700")

# gdf.plot(column="conc", legend=True)
# plt.show()

gdf.head()

         Easting  Northing      conc               geometry
4130453   518740    169900  8.973591  POINT (518740 169900)
4130456   518800    169900  8.976542  POINT (518800 169900)
4135707   518700    169860  8.990891  POINT (518700 169860)
4138328   518580    169840  8.987017  POINT (518580 169840)
4140965   518780    169820  9.018723  POINT (518780 169820)

In [35]:
gdf.to_json()

'{"type": "FeatureCollection", "features": [{"id": "4130453", "type": "Feature", "properties": {"Easting": 518740, "Northing": 169900, "conc": 8.973591}, "geometry": {"type": "Point", "coordinates": [518740.0, 169900.0]}}, {"id": "4130456", "type": "Feature", "properties": {"Easting": 518800, "Northing": 169900, "conc": 8.976542}, "geometry": {"type": "Point", "coordinates": [518800.0, 169900.0]}}, {"id": "4135707", "type": "Feature", "properties": {"Easting": 518700, "Northing": 169860, "conc": 8.990891}, "geometry": {"type": "Point", "coordinates": [518700.0, 169860.0]}}, {"id": "4138328", "type": "Feature", "properties": {"Easting": 518580, "Northing": 169840, "conc": 8.987017}, "geometry": {"type": "Point", "coordinates": [518580.0, 169840.0]}}, {"id": "4140965", "type": "Feature", "properties": {"Easting": 518780, "Northing": 169820, "conc": 9.018723}, "geometry": {"type": "Point", "coordinates": [518780.0, 169820.0]}}, {"id": "4146205", "type": "Feature", "properties": {"Easting": 518560, "Northing": 169780, "conc": 9.020031}, "geometry": {"type": "Point", "coordinates": [518560.0, 169780.0]}}, {"id": "4146209", "type": "Feature", "properties": {"Easting": 518640, "Northing": 169780, "conc": 9.021122}, "geometry": {"type": "Point", "coordinates": [518640.0, 169780.0]}}, {"id": "4151463", "type": "Feature", "properties": {"Easting": 518740, "Northing": 169740, "conc": 8.987494}, "geometry": {"type": "Point", "coordinates": [518740.0, 169740.0]}}, {"id": "4154082", "type": "Feature", "properties": {"Easting": 518640, "Northing": 169720, "conc": 9.051048}, "geometry": {"type": "Point", "coordinates": [518640.0, 169720.0]}}, {"id": "4154083", "type": "Feature", "properties": {"Easting": 518660, "Northing": 169720, "conc": 9.04655}, "geometry": {"type": "Point", "coordinates": [518660.0, 169720.0]}}, {"id": "4156700", "type": "Feature", "properties": {"Easting": 518540, "Northing": 169700, "conc": 9.022141}, "geometry": {"type": "Point", "coordinates": [518540.0, 169700.0]}}, {"id": "4156701", "type": "Feature", "properties": {"Easting": 518560, "Northing": 169700, "conc": 9.091623}, "geometry": {"type": "Point", "coordinates": [518560.0, 169700.0]}}, {"id": "4156702", "type": "Feature", "properties": {"Easting": 518580, "Northing": 169700, "conc": 9.004419}, "geometry": {"type": "Point", "coordinates": [518580.0, 169700.0]}}, {"id": "4161945", "type": "Feature", "properties": {"Easting": 518540, "Northing": 169660, "conc": 9.092828}, "geometry": {"type": "Point", "coordinates": [518540.0, 169660.0]}}, {"id": "4164568", "type": "Feature", "properties": {"Easting": 518540, "Northing": 169640, "conc": 9.117596}, "geometry": {"type": "Point", "coordinates": [518540.0, 169640.0]}}, {"id": "4164573", "type": "Feature", "properties": {"Easting": 518640, "Northing": 169640, "conc": 9.047789}, "geometry": {"type": "Point", "coordinates": [518640.0, 169640.0]}}, {"id": "4167190", "type": "Feature", "properties": {"Easting": 518540, "Northing": 169620, "conc": 9.186471}, "geometry": {"type": "Point", "coordinates": [518540.0, 169620.0]}}, {"id": "4167191", "type": "Feature", "properties": {"Easting": 518560, "Northing": 169620, "conc": 8.987647}, "geometry": {"type": "Point", "coordinates": [518560.0, 169620.0]}}, {"id": "4167192", "type": "Feature", "properties": {"Easting": 518580, "Northing": 169620, "conc": 9.242498}, "geometry": {"type": "Point", "coordinates": [518580.0, 169620.0]}}, {"id": "4167193", "type": "Feature", "properties": {"Easting": 518600, "Northing": 169620, "conc": 9.052608}, "geometry": {"type": "Point", "coordinates": [518600.0, 169620.0]}}, {"id": "4167202", "type": "Feature", "properties": {"Easting": 518780, "Northing": 169620, "conc": 8.984079}, "geometry": {"type": "Point", "coordinates": [518780.0, 169620.0]}}, {"id": "4167203", "type": "Feature", "properties": {"Easting": 518800, "Northing": 169620, "conc": 9.047733}, "geometry": {"type": "Point", "coordinates": [518800.0, 169620.0]}}, {"id": "4169810", "type": "Feature", "properties": {"Easting": 518500, "Northing": 169600, "conc": 9.029213}, "geometry": {"type": "Point", "coordinates": [518500.0, 169600.0]}}, {"id": "4169811", "type": "Feature", "properties": {"Easting": 518520, "Northing": 169600, "conc": 9.028079}, "geometry": {"type": "Point", "coordinates": [518520.0, 169600.0]}}, {"id": "4169821", "type": "Feature", "properties": {"Easting": 518720, "Northing": 169600, "conc": 9.062172}, "geometry": {"type": "Point", "coordinates": [518720.0, 169600.0]}}, {"id": "4169822", "type": "Feature", "properties": {"Easting": 518740, "Northing": 169600, "conc": 9.013828}, "geometry": {"type": "Point", "coordinates": [518740.0, 169600.0]}}], "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:EPSG::27700"}}}'

In [37]:
# initialize the map and store it in a m object
london_centre = [51.51, -0.12]

m = folium.Map(location=london_centre, zoom_start=10)

folium.Choropleth(
    geo_data=gdf,
    name="PM2.5_90thPercentile",
    data=gdf,
    columns=["conc"],
    key_on="features.id",
    fill_color="YlGn",
    fill_opacity=0.7,
    line_opacity=.1,
    legend_name="PM 2.5 concentration (micrograms/cubic metre)",
).add_to(m)

folium.LayerControl().add_to(m)

m

IndexError: list index out of range